@baseurl = http://localhost:3001

GET {{baseurl}}/api/persons

###

GET {{baseurl}}/api/persons/654a67be6334b399500db2ef

###

DELETE {{baseurl}}/api/persons/654940223a84ed64b046061e

###

POST {{baseurl}}/api/persons
Content-Type: application/json

{
  "name": "Wesley Damasceno",
  "number": "12-43-234345"
}